services:
  db:
    image: postgres:16
    container_name: pg_nest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Argentina/Buenos_Aires
      PGTZ: America/Argentina/Buenos_Aires
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${APP_PORT:-3000}:3000"
#    command: sh -c "npm run migration:run && npm run start:dev" #prod
    command: npm run start:dev:migrate #dev
    volumes:
#      - .:/usr/src/app #prod
#      - /usr/src/app/node_modules #prod
      - .:/app #dev
      - /app/node_modules #dev

volumes:
  pgdata:
